### PR TITLE
[Table] Fix alignments in Table row groups

### LINKED ISSUE #495: Fix alignments in Table row groups
- __Blue thing `⌞` on the left__: Align vertically at center when row is taller than normal
- __Expand button__: Align right or prevent it's column from expanding when table has free space

image

### PR DESCRIPTION
**Pull request by fgameiro**
## Closes Issues

* Closes #495 

### Reviewer 1

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### Reviewer 2

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### CODE REVIEW

File: packages/table/src/Table.js [hunk 1]
```diff
@@ -219,13 +220,15 @@ class Table extends React.Component {
...
       : "wg-small-arrow-bottom";
     return (
-      <Button
-        icon={icon}
-        onClick={e => {
-          this.expandToggleClicked(rowKey);
-          e.stopPropagation();
-        }}
-      />
+      <ButtonContainer>
```
Comment (alcferreira) [inline packages/table/src/Table.js]: `ButtonContainer` is a `div` with flex and justify-content only.
I think it'd be better to set these styles on `BodyCell` component.

This way we would have this:

```
<div className="class-name-x">
  <Button
    icon={icon}
    onClick={e => {
      this.expandToggleClicked(rowKey);
      e.stopPropagation();
    }}
  />
</div>
```

And `BodyCell` would be like this:
```
export const BodyCell = styled.td`
  text-align: ${textAlign};
  background-color: ${cellBg};

  .class-name-x {
    display: flex;
    justify-content: flex-end;
  }
`;
```

**Comment by alcferreira** [comment]
Please set a width to some story so we can easily see that the expand button is right-aligned.
I had to do it manually to check the changes...

File: packages/table/src/Table.js (hunk 1 above)
Comment (vNakamura) [reply packages/table/src/Table.js]: From this comment I noticed that we have this `text-align` rule already, which can be set by the `align` prop. So you can simple use this at line 188: 
```
<BodyCell className="cell" align="right" {...rowProps}>
```
