### PR TITLE
Fix Search Field inputValue when items change after mount

### LINKED ISSUE #469: Search Field - inputValue is not updated when items change after mount
When, after mount, `items` change, and `value` is the same, we don't update the state `inputValue`, therefore we may show incorrect value on Search Field.

The following sequence illustrates this problem happening on webapp:
inputvalue

### PR DESCRIPTION
**Pull request by fgameiro**
## Closes Issues

* Closes #469 
### Reviewer 1

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### Reviewer 2

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### CODE REVIEW

File: packages/search-field/src/SearchField.js [hunk 1]
```diff
@@ -65,6 +65,7 @@ class SearchField extends React.Component {
 
     if (!isEqual(prevProps.items, this.props.items)) {
       this.setState({ items: this.props.items });
+      this.setValueFromProps();
```
Comment (alcferreira) [inline packages/search-field/src/SearchField.js]: I guess we should have an unit test for this because snapshot by itself won't cover this case.

Comment (fgameiro) [reply packages/search-field/src/SearchField.js]: Added!
