### PR TITLE
[Button] Fix white space

### LINKED ISSUE #1007: [Button] text should not break line
Current behavior:
image

Expected behavior:
image

### PR DESCRIPTION
**Pull request by alcferreira**
## Closes Issues

* Closes #1007

### Reviewer 1

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### Reviewer 2

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### CODE REVIEW

File: packages/button/src/styledComponents/Button.js [hunk 1]
```diff
@@ -22,6 +22,8 @@ function themeStyle(props) {
     border: ${normal?.border || `solid 1px ${colors.GREY_16}`};
     box-shadow: ${normal?.boxShadow || `0px 2px 2px 0px ${colors.GREY_16}`};
 
+    white-space: nowrap;
```
Comment (vNakamura) [inline packages/button/src/styledComponents/Button.js:25]: How should it behave when there's no room for the text?
This is the current behavior:
image

We can truncate it with ellipsis by wrapping the text by a `span` with this style:
```css
text-overflow: ellipsis;
overflow: hidden;
```
image

Comment (alcferreira) [reply packages/button/src/styledComponents/Button.js:25]: true that... thankss

**Review by vNakamura — APPROVED** [review]
