### PR TITLE
Fix select handling of value equal to zero

### LINKED ISSUE #452: Select - Incorrect handling when value is equal to zero
When we have to handle an item with `value = 0`, our currently select input doesn't get its label or get it wrong.

## Current behavior:
select-zero-error

## Expected behavior:
select-zero-fix

### PR DESCRIPTION
**Pull request by fgameiro**
## Closes Issues

* Closes #452 

### Reviewer 1

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### Reviewer 2

* [ ] Functions properly
* [ ] Good readability, clarity and overall quality
* [ ] Has tests
* [ ] Has docs

### CODE REVIEW

File: packages/input-select/src/Select.js [hunk 1]
```diff
@@ -62,14 +62,18 @@ class Select extends React.Component {
...
-    return item && item.label;
+    if (item) {
+      return item.label;
+    }
   };
 
   componentWillReceiveProps = newProps => {
     if (
-      (newProps.value &&
+      ((newProps.value || newProps.value === 0) &&
```
Comment (alcferreira) [inline packages/input-select/src/Select.js]: Add a unit test to cover this change

File: packages/input-select/src/Select.story.js [hunk 2]
```diff
@@ -219,4 +219,56 @@ storiesOf("Select Input", module)
         maxHeight="150px"
       />
     ))
+  )
+  .add(
+    "Receiving new value",
```
Comment (alcferreira) [inline packages/input-select/src/Select.story.js]: For testing purposes, it'd be better to write unit tests...

File: packages/input-select/src/Select.js (hunk 1 above)
Comment (fgameiro) [reply packages/input-select/src/Select.js]: done!
